# Generated by Django 5.0.5 on 2024-05-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_quarto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORTO', 'Conforto'), ('LUXO', 'Luxo')], max_length=15),
        ),
    ]
