# Generated by Django 5.0.5 on 2024-05-16 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
